### ISSUE TITLE
Verification Protocols rework - electrodes

### ISSUE THREAD

**Issue by crexroth** [COSMIIC-Inc/Implantables-Electrodes#1]
Could you please change these things...
* Requirements addressed should reference that tag for the ID from the corresponding NNP-REQ document?
* The Revision History should be updated to have your name as author and date. Jenna put "First version of document" for summary of changes.
* Remove the approval history section from the end of document and table of contents.
You can choose if you want to port things over into the updated template I made last month (automatic bullet points and table of contents) or if you just want to work with what you already have. Whatever is faster.

Jenna just made these same changes for her Network Cable test reports.

I uploaded the reqs document

**Comment by dr-mh** [comment]
All done:)
